-- ===========================================
-- Weekly Classes Schedule - Database Setup
-- ===========================================

-- 1. Create Classes Table
-- Stores all available class names (e.g., Tawheed, Seerah, Arabic Classes)
CREATE TABLE public.classes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- Policies for Classes
CREATE POLICY "Classes are viewable by everyone."
  ON classes FOR SELECT
  USING (true);

CREATE POLICY "Only admins can manage classes."
  ON classes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 2. Create Teachers Table
-- Stores all teacher names (e.g., Sh. Yousaf, Dr. Jawad, Sh. Abdul Aziz)
CREATE TABLE public.teachers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;

-- Policies for Teachers
CREATE POLICY "Teachers are viewable by everyone."
  ON teachers FOR SELECT
  USING (true);

CREATE POLICY "Only admins can manage teachers."
  ON teachers FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 3. Create Weekly Schedules Table
-- Maps classes to specific days with teachers and optional timing
CREATE TABLE public.weekly_schedules (
  id bigint generated by default as identity primary key,
  day_of_week int not null CHECK (day_of_week >= 1 AND day_of_week <= 7), -- 1=Monday, 7=Sunday
  class_id bigint not null references classes(id) on delete cascade,
  teacher_id bigint references teachers(id) on delete set null,
  start_time text, -- e.g., "6:00 PM" (nullable)
  end_time text,   -- e.g., "7:30 PM" (nullable)
  schedule_type text default 'weekly' CHECK (schedule_type IN ('weekly', 'quran')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.weekly_schedules ENABLE ROW LEVEL SECURITY;

-- Policies for Weekly Schedules
CREATE POLICY "Schedules are viewable by everyone."
  ON weekly_schedules FOR SELECT
  USING (true);

CREATE POLICY "Only admins can manage schedules."
  ON weekly_schedules FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- 4. Insert Sample Data
-- Sample Classes
INSERT INTO public.classes (name, description) VALUES
  ('Tawheed', 'Islamic monotheism and belief'),
  ('Seerah', 'Life and teachings of Prophet Muhammad (PBUH)'),
  ('Arabic Classes', 'Learning Arabic language'),
  ('Tafseer', 'Quranic exegesis and interpretation'),
  ('Zaad ul Ma''aal', 'Provisions for the Hereafter'),
  ('Adult Qur''an Class', 'Qur''an recitation for adults'),
  ('Kids Qur''an Class', 'Qur''an learning for children');

-- Sample Teachers
INSERT INTO public.teachers (name, bio) VALUES
  ('Sh. Yousaf', 'Senior scholar and educator'),
  ('Dr. Jawad', 'Islamic studies specialist'),
  ('Sh. Abdul Aziz', 'Qur''an recitation expert');

-- Sample Weekly Schedules
-- Weekly Schedule Section
INSERT INTO public.weekly_schedules (day_of_week, class_id, teacher_id, schedule_type) VALUES
  (1, (SELECT id FROM classes WHERE name = 'Tawheed'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), 'weekly'),
  (2, (SELECT id FROM classes WHERE name = 'Arabic Classes'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), 'weekly'),
  (3, (SELECT id FROM classes WHERE name = 'Seerah'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), 'weekly'),
  (4, (SELECT id FROM classes WHERE name = 'Arabic Classes'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), 'weekly'),
  (5, (SELECT id FROM classes WHERE name = 'Tafseer'), (SELECT id FROM teachers WHERE name = 'Dr. Jawad'), 'weekly'),
  (7, (SELECT id FROM classes WHERE name = 'Zaad ul Ma''aal'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), 'weekly');

-- Qur'an Classes Section
INSERT INTO public.weekly_schedules (day_of_week, class_id, teacher_id, schedule_type) VALUES
  (1, (SELECT id FROM classes WHERE name = 'Adult Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Abdul Aziz'), 'quran'),
  (2, (SELECT id FROM classes WHERE name = 'Adult Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Abdul Aziz'), 'quran'),
  (3, (SELECT id FROM classes WHERE name = 'Adult Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Abdul Aziz'), 'quran');

-- Kids Qur'an Class with timing
INSERT INTO public.weekly_schedules (day_of_week, class_id, teacher_id, start_time, end_time, schedule_type) VALUES
  (1, (SELECT id FROM classes WHERE name = 'Kids Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), '6:00 PM', '7:30 PM', 'quran'),
  (2, (SELECT id FROM classes WHERE name = 'Kids Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), '6:00 PM', '7:30 PM', 'quran'),
  (3, (SELECT id FROM classes WHERE name = 'Kids Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), '6:00 PM', '7:30 PM', 'quran'),
  (4, (SELECT id FROM classes WHERE name = 'Kids Qur''an Class'), (SELECT id FROM teachers WHERE name = 'Sh. Yousaf'), '6:00 PM', '7:30 PM', 'quran');
