-- 1. Create Khateebs Table (Idempotent)
create table if not exists public.khateebs (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS (Safe to run multiple times, command itself is idempotent usually, but policies need checks)
alter table public.khateebs enable row level security;

-- 3. Policies for Khateebs (Drop first to avoid 'already exists' error)
drop policy if exists "Khateebs are viewable by everyone." on khateebs;
create policy "Khateebs are viewable by everyone."
  on khateebs for select
  using ( true );

drop policy if exists "Only admins can manage khateebs." on khateebs;
create policy "Only admins can manage khateebs."
  on khateebs for all
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- 4. Update Jummah Configurations Table (Check if column exists)
do $$
begin
    if not exists (select 1 from information_schema.columns 
                   where table_name='jummah_configurations' and column_name='khateeb_name') then
        alter table public.jummah_configurations add column khateeb_name text;
    end if;
end $$;

-- Optional: If we want strict linking
-- alter table public.jummah_configurations add column khateeb_id bigint references public.khateebs(id);
