-- =============================================================================
-- FIX: Prayer times & Jummah notifications (OneSignal)
-- =============================================================================
-- 1. Use the SAME OneSignal app_id as your Flutter app and events trigger
--    (4428e176-2a7f-4d7f-9c28-4ebec13b5001). The manual function was using a
--    different app_id, so push was going to the wrong app.
-- 2. Parse prayer times robustly (12h AM/PM and 24h).
-- 3. Deduplicate: send "30 min before" and "on time" only once per day per slot.
-- 4. Jummah on Friday from jummah_configurations (khutbah_time).
-- =============================================================================

-- Enable extensions if not already
create extension if not exists pg_net;
create extension if not exists pg_cron;

-- -----------------------------------------------------------------------------
-- 1. Table to avoid sending the same notification twice for the same (date, slot, time).
--    Deduplication is by actual prayer time so changing a prayer time and testing again
--    will send a new notification when the new time comes.
-- -----------------------------------------------------------------------------
create table if not exists public.prayer_notification_sent (
  id bigint generated by default as identity primary key,
  notify_date date not null,
  slot text not null,  -- e.g. 'fajr_30', 'fajr_on', 'dhuhr_30', 'jummah_30', ...
  prayer_time time not null,  -- the actual adhan time we notified for (so changing time = new notification)
  sent_at timestamptz not null default now(),
  unique (notify_date, slot, prayer_time)
);

-- If table already existed without prayer_time, add column and fix constraint
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'prayer_notification_sent'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'prayer_notification_sent' and column_name = 'prayer_time'
  ) then
    alter table public.prayer_notification_sent add column prayer_time time;
    update public.prayer_notification_sent set prayer_time = (sent_at at time zone 'utc')::time where prayer_time is null;
    alter table public.prayer_notification_sent alter column prayer_time set not null;
    alter table public.prayer_notification_sent drop constraint if exists prayer_notification_sent_notify_date_slot_key;
    alter table public.prayer_notification_sent add constraint prayer_notification_sent_notify_date_slot_prayer_time_key unique (notify_date, slot, prayer_time);
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 2. Manual notification function – MUST use same app_id as Flutter app
--    (Replace os_api_key with your OneSignal REST API key if different.)
-- -----------------------------------------------------------------------------
create or replace function public.send_onesignal_notification_manual(title text, body text)
returns void as $$
declare
  -- Use same app_id as events trigger and Flutter app (4428e176...)
  os_app_id text := '4428e176-2a7f-4d7f-9c28-4ebec13b5001';
  os_api_key text := 'os_v2_app_iquoc5rkp5gx7hbij27mco2qahav72yvfclu2jexb3dw457asdftzhf4vtf5e45ozbln6ruhu5g3j6wcw6ilapalnnjk4by6x6mn4ca';
begin
  perform net.http_post(
      url:='https://onesignal.com/api/v1/notifications',
      headers:=jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Basic ' || os_api_key
      ),
      body:=jsonb_build_object(
          'app_id', os_app_id,
          'headings', jsonb_build_object('en', title),
          'contents', jsonb_build_object('en', body),
          'included_segments', jsonb_build_array('All')
      )
  );
end;
$$ language plpgsql security definer;

-- -----------------------------------------------------------------------------
-- 3. Helper: parse time string from DB (supports "5:30 AM", "12:15 PM", "17:30")
-- -----------------------------------------------------------------------------
create or replace function public.parse_prayer_time(ts text)
returns time language plpgsql as $$
declare
  t time;
  u text;
begin
  if ts is null or trim(ts) = '' then return null; end if;
  u := trim(ts);
  begin
    -- 12h with AM
    if upper(u) like '%AM' then
      t := to_timestamp(u, 'HH12:MI AM')::time;
      return t;
    end if;
    -- 12h with PM
    if upper(u) like '%PM' then
      t := to_timestamp(u, 'HH12:MI PM')::time;
      return t;
    end if;
    -- 24h (e.g. 05:30, 17:30)
    t := to_timestamp(u, 'HH24:MI')::time;
    return t;
  exception when others then
    return null;
  end;
end;
$$;

-- -----------------------------------------------------------------------------
-- 4. Mark a slot+time as sent (so we send once per prayer time; changing time = new notification)
-- -----------------------------------------------------------------------------
create or replace function public.try_send_prayer_notification(
  p_date date,
  p_slot text,
  p_prayer_time time,
  p_title text,
  p_body text
) returns boolean language plpgsql security definer as $$
begin
  -- Already sent today for this slot at this exact prayer time?
  if exists (
    select 1 from public.prayer_notification_sent
    where notify_date = p_date and slot = p_slot and prayer_time = p_prayer_time
  ) then
    return false;
  end if;
  perform public.send_onesignal_notification_manual(p_title, p_body);
  insert into public.prayer_notification_sent (notify_date, slot, prayer_time)
  values (p_date, p_slot, p_prayer_time)
  on conflict (notify_date, slot, prayer_time) do nothing;
  return true;
end;
$$;

-- -----------------------------------------------------------------------------
-- 5. Main cron logic: check prayer times and Jummah. Fire when current minute
--    exactly matches prayer minute (full minute = 100% precise, won't miss).
--    Deduplication by (date, slot, prayer_time) so changing a prayer time and
--    testing again sends when the new time comes.
-- -----------------------------------------------------------------------------
create or replace function public.check_prayer_times()
returns void language plpgsql security definer as $$
declare
  target_timezone text := 'Australia/Melbourne';
  cur_ts timestamptz := now();
  cur_time time;
  today_date date;
  rec record;
  p_time time;
  prayer_name text;
  is_friday boolean;
  jummah_time_str text;
  slot text;
  same_minute boolean;
begin
  cur_time := (cur_ts at time zone target_timezone)::time;
  today_date := (cur_ts at time zone target_timezone)::date;
  is_friday := extract(isodow from (cur_ts at time zone target_timezone)) = 5;

  -- Today's prayer row (always use latest data; if you change time, we use new time)
  select * into rec from public.prayer_times where date = today_date;
  if rec is null then return; end if;

  -- Five daily prayers
  foreach prayer_name in array array['fajr', 'dhuhr', 'asr', 'maghrib', 'isha']
  loop
    case prayer_name
      when 'fajr' then p_time := public.parse_prayer_time(rec.fajr);
      when 'dhuhr' then p_time := public.parse_prayer_time(rec.dhuhr);
      when 'asr' then p_time := public.parse_prayer_time(rec.asr);
      when 'maghrib' then p_time := public.parse_prayer_time(rec.maghrib);
      when 'isha' then p_time := public.parse_prayer_time(rec.isha);
      else p_time := null;
    end case;

    if p_time is null then continue; end if;

    -- 30 minutes before (Adhan): current minute exactly = (prayer_time - 30 min)
    same_minute := extract(hour from cur_time) = extract(hour from (p_time - interval '30 minutes'))
               and extract(minute from cur_time) = extract(minute from (p_time - interval '30 minutes'));
    if same_minute then
      slot := prayer_name || '_30';
      perform public.try_send_prayer_notification(
        today_date, slot, p_time,
        initcap(prayer_name),
        'Prepare for prayer. Adhan in 30 minutes.'
      );
    end if;

    -- On time (Iqamah): current minute exactly = prayer minute (full minute = precise, won't miss)
    same_minute := extract(hour from cur_time) = extract(hour from p_time)
               and extract(minute from cur_time) = extract(minute from p_time);
    if same_minute then
      slot := prayer_name || '_on';
      perform public.try_send_prayer_notification(
        today_date, slot, p_time,
        initcap(prayer_name),
        'Iqamah will start Shortly.'
      );
    end if;
  end loop;

  -- Jummah (Friday only): use khutbah_time from jummah_configurations
  if is_friday then
    select khutbah_time into jummah_time_str from public.jummah_configurations limit 1;
    if jummah_time_str is not null and trim(jummah_time_str) <> '' then
      p_time := public.parse_prayer_time(jummah_time_str);
      if p_time is not null then
        same_minute := extract(hour from cur_time) = extract(hour from (p_time - interval '30 minutes'))
                   and extract(minute from cur_time) = extract(minute from (p_time - interval '30 minutes'));
        if same_minute then
          perform public.try_send_prayer_notification(
            today_date, 'jummah_30', p_time,
            'Jummah',
            'Prepare for Jummah. Khutbah in 30 minutes.'
          );
        end if;
        same_minute := extract(hour from cur_time) = extract(hour from p_time)
                   and extract(minute from cur_time) = extract(minute from p_time);
        if same_minute then
          perform public.try_send_prayer_notification(
            today_date, 'jummah_on', p_time,
            'Jummah',
            'Khutbah has started.'
          );
        end if;
      end if;
    end if;
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Schedule cron to run every minute (remove old job first if exists)
-- -----------------------------------------------------------------------------
do $$
declare
  jid bigint;
begin
  for jid in select jobid from cron.job where command like '%check_prayer_times%'
  loop
    perform cron.unschedule(jid);
  end loop;
end;
$$;
select cron.schedule(
  'prayer-check-job',
  '* * * * *',
  $$ select public.check_prayer_times() $$
);
